-- Analizador Léxico UMG — PostgreSQL 16+
-- Script único para una base de datos nueva. No incluye usuarios ni secretos.

BEGIN;

CREATE TABLE usuarios (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo              varchar(150) NOT NULL,
    telefono            varchar(20) NOT NULL,
    fecha_nacimiento    timestamptz NOT NULL,
    nickname            varchar(50) NOT NULL,
    password_hash       text NOT NULL,
    metodo_notificacion varchar(20) NOT NULL DEFAULT 'email',
    foto_original       text,
    foto_modificada     text,
    rol                 varchar(20) NOT NULL DEFAULT 'ANALISTA',
    activo              boolean NOT NULL DEFAULT true,
    fecha_registro      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_usuarios_correo CHECK (char_length(trim(correo)) > 3),
    CONSTRAINT ck_usuarios_telefono CHECK (char_length(trim(telefono)) BETWEEN 8 AND 20),
    CONSTRAINT ck_usuarios_nickname CHECK (char_length(trim(nickname)) BETWEEN 3 AND 50),
    CONSTRAINT ck_usuarios_notificacion CHECK (metodo_notificacion IN ('email', 'whatsapp', 'ambos')),
    CONSTRAINT ck_usuarios_rol CHECK (rol IN ('ADMIN', 'SUPERVISOR', 'ANALISTA')),
    CONSTRAINT ck_usuarios_password CHECK (char_length(trim(password_hash)) > 0)
);

-- Metadatos del archivo fuente. El contenido se almacena fuera de la base de datos;
-- el hash permite verificar que un archivo no ha cambiado entre análisis.
CREATE TABLE archivos_usuario (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          integer NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    nombre_original     varchar(255) NOT NULL,
    ubicacion_almacen   text NOT NULL,
    hash_contenido      char(64) NOT NULL,
    mime_type           varchar(100) NOT NULL DEFAULT 'text/plain',
    tamano_bytes        bigint NOT NULL,
    fecha_carga         timestamptz NOT NULL DEFAULT now(),
    activo              boolean NOT NULL DEFAULT true,

    CONSTRAINT ck_archivo_nombre CHECK (char_length(trim(nombre_original)) > 0),
    CONSTRAINT ck_archivo_ubicacion CHECK (char_length(trim(ubicacion_almacen)) > 0),
    CONSTRAINT ck_archivo_hash CHECK (hash_contenido ~ '^[A-Fa-f0-9]{64}$'),
    CONSTRAINT ck_archivo_tamano CHECK (tamano_bytes >= 0)
);

-- Historial de fotografías de perfil. Solo guarda referencias protegidas de archivo
-- y su hash; no define reconocimiento facial ni almacena plantillas biométricas.
CREATE TABLE fotografias_usuario (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          integer NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    tipo                varchar(20) NOT NULL,
    ubicacion_almacen   text NOT NULL,
    hash_contenido      char(64) NOT NULL,
    estado              varchar(20) NOT NULL DEFAULT 'activa',
    fecha_registro      timestamptz NOT NULL DEFAULT now(),
    reemplazada_en      timestamptz,

    CONSTRAINT ck_fotografia_tipo CHECK (tipo IN ('original', 'modificada')),
    CONSTRAINT ck_fotografia_estado CHECK (estado IN ('activa', 'reemplazada', 'revocada')),
    CONSTRAINT ck_fotografia_ubicacion CHECK (char_length(trim(ubicacion_almacen)) > 0),
    CONSTRAINT ck_fotografia_hash CHECK (hash_contenido ~ '^[A-Fa-f0-9]{64}$')
);

-- Registro auditable de carnets emitidos. El QR se conserva como hash, no como token.
CREATE TABLE credenciales_usuario (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          integer NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    codigo_publico      uuid NOT NULL UNIQUE,
    codigo_qr_hash      char(64) NOT NULL,
    estado              varchar(20) NOT NULL DEFAULT 'emitida',
    fecha_emision       timestamptz NOT NULL DEFAULT now(),
    fecha_vencimiento   timestamptz,
    fecha_revocacion    timestamptz,
    motivo_revocacion   varchar(250),

    CONSTRAINT ck_credencial_estado CHECK (estado IN ('emitida', 'vencida', 'revocada')),
    CONSTRAINT ck_credencial_qr_hash CHECK (codigo_qr_hash ~ '^[A-Fa-f0-9]{64}$'),
    CONSTRAINT ck_credencial_fechas CHECK (
        fecha_vencimiento IS NULL OR fecha_vencimiento > fecha_emision
    )
);

CREATE TABLE bitacora_login (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  integer NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    fecha_hora  timestamptz NOT NULL DEFAULT now(),
    ip_origen   varchar(45),
    user_agent  varchar(300),
    resultado   varchar(20) NOT NULL,
    metodo      varchar(20) NOT NULL,

    CONSTRAINT ck_bitacora_resultado CHECK (resultado IN ('exitoso', 'fallido')),
    CONSTRAINT ck_bitacora_metodo CHECK (metodo IN ('password', 'facial', 'qr'))
);

CREATE TABLE resultado_analisis (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      integer NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    archivo_id      integer REFERENCES archivos_usuario(id) ON DELETE SET NULL,
    idioma          varchar(30) NOT NULL,
    nombre_archivo  text NOT NULL,
    total_palabras  integer NOT NULL,
    total_tokens    integer NOT NULL,
    detalle_json    jsonb NOT NULL DEFAULT '{}'::jsonb,
    fecha_analisis  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_resultado_idioma CHECK (idioma IN ('español', 'inglés', 'ruso', 'chino', 'árabe')),
    CONSTRAINT ck_resultado_archivo CHECK (char_length(trim(nombre_archivo)) > 0),
    CONSTRAINT ck_resultado_totales CHECK (total_palabras >= 0 AND total_tokens >= 0)
);

CREATE UNIQUE INDEX ux_usuarios_correo ON usuarios (lower(correo));
CREATE UNIQUE INDEX ux_usuarios_nickname ON usuarios (lower(nickname));
CREATE INDEX ix_archivos_usuario_fecha ON archivos_usuario (usuario_id, fecha_carga DESC);
CREATE INDEX ix_fotografias_usuario_estado ON fotografias_usuario (usuario_id, estado, fecha_registro DESC);
CREATE INDEX ix_credenciales_usuario_estado ON credenciales_usuario (usuario_id, estado, fecha_emision DESC);
CREATE INDEX ix_bitacora_login_usuario_fecha ON bitacora_login (usuario_id, fecha_hora DESC);
CREATE INDEX ix_resultado_analisis_usuario_fecha ON resultado_analisis (usuario_id, fecha_analisis DESC);
CREATE INDEX ix_resultado_analisis_archivo_fecha ON resultado_analisis (archivo_id, fecha_analisis DESC);

COMMIT;
