-- Lenguajes Formales y Autómatas — esquema PostgreSQL
-- Generado desde la migración 20260804025844_InitialCreate.
-- Ejecutar una sola vez sobre una base de datos PostgreSQL vacía.

BEGIN;

CREATE TABLE IF NOT EXISTS usuarios (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo character varying(150) NOT NULL,
    telefono character varying(20) NOT NULL,
    fecha_nacimiento timestamp with time zone NOT NULL,
    nickname character varying(50) NOT NULL,
    password_hash text NOT NULL,
    metodo_notificacion character varying(20) NOT NULL,
    foto_original text NULL,
    foto_modificada text NULL,
    rol character varying(20) NOT NULL,
    activo boolean NOT NULL,
    fecha_registro timestamp with time zone NOT NULL,
    CONSTRAINT "CK_usuarios_correo" CHECK (length(trim(correo)) > 3),
    CONSTRAINT "CK_usuarios_telefono" CHECK (length(trim(telefono)) BETWEEN 8 AND 20),
    CONSTRAINT "CK_usuarios_nickname" CHECK (length(trim(nickname)) BETWEEN 3 AND 50),
    CONSTRAINT "CK_usuarios_notificacion" CHECK (metodo_notificacion IN ('email', 'whatsapp', 'ambos')),
    CONSTRAINT "CK_usuarios_rol" CHECK (rol IN ('ADMIN', 'SUPERVISOR', 'ANALISTA')),
    CONSTRAINT "CK_usuarios_foto_original" CHECK (foto_original IS NULL OR length(trim(foto_original)) > 0),
    CONSTRAINT "CK_usuarios_foto_modificada" CHECK (foto_modificada IS NULL OR length(trim(foto_modificada)) > 0)
);

CREATE TABLE IF NOT EXISTS bitacora_login (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id integer NOT NULL,
    fecha_hora timestamp with time zone NOT NULL,
    ip_origen character varying(45) NULL,
    user_agent character varying(300) NULL,
    resultado character varying(20) NOT NULL,
    metodo character varying(20) NOT NULL,
    CONSTRAINT "CK_bitacora_resultado" CHECK (resultado IN ('exitoso', 'fallido')),
    CONSTRAINT "CK_bitacora_metodo" CHECK (metodo IN ('password', 'facial', 'qr')),
    CONSTRAINT "FK_bitacora_login_usuarios_usuario_id"
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS resultado_analisis (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id integer NOT NULL,
    idioma character varying(30) NOT NULL,
    nombre_archivo text NOT NULL,
    total_palabras integer NOT NULL,
    total_tokens integer NOT NULL,
    detalle_json text NOT NULL,
    fecha_analisis timestamp with time zone NOT NULL,
    CONSTRAINT "CK_resultado_idioma" CHECK (idioma IN ('español', 'inglés', 'ruso', 'chino', 'árabe')),
    CONSTRAINT "CK_resultado_archivo" CHECK (length(trim(nombre_archivo)) > 0),
    CONSTRAINT "CK_resultado_totales" CHECK (total_palabras >= 0 AND total_tokens >= 0),
    CONSTRAINT "FK_resultado_analisis_usuarios_usuario_id"
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_usuarios_correo" ON usuarios (correo);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_usuarios_nickname" ON usuarios (nickname);
CREATE INDEX IF NOT EXISTS "IX_bitacora_login_usuario_id" ON bitacora_login (usuario_id);
CREATE INDEX IF NOT EXISTS "IX_resultado_analisis_usuario_id" ON resultado_analisis (usuario_id);

-- Cuenta inicial. Cambia la contraseña desde Perfil tras el primer acceso.
INSERT INTO usuarios (
    id, correo, telefono, fecha_nacimiento, nickname, password_hash,
    metodo_notificacion, rol, activo, fecha_registro
)
VALUES (
    1, 'admin@lenguajes.umg.edu.gt', '50200000000',
    TIMESTAMPTZ '1990-01-01 00:00:00+00', 'admin',
    '$2a$11$/BUgxH0omkS815S/Mn0Gj.uyDU1bBvlsof/OIkazK6aINOEAxYuoi',
    'email', 'ADMIN', TRUE, TIMESTAMPTZ '2026-01-01 00:00:00+00'
)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('usuarios', 'id'),
              GREATEST((SELECT COALESCE(MAX(id), 1) FROM usuarios), 1));

COMMIT;
